# Generated by Django 5.0.6 on 2024-06-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_compra_data_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
