# Generated by Django 5.0.6 on 2024-06-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_vendedor_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
